# Welcome to DemonWolf Boilerplate
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in HTML files,
# you will see them access via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the template via {{ site.myvariable }}.
title: "JslHub"
email: jsl@jslhub.com
description: Just JSL being JSL...
keywords:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jslhub.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: mrdemonwolf
encoding: UTF-8
brand-color: '#00328d'

# Build settings
markdown: kramdown
permalink: pretty # Enabled pretty urls /test/ other then test.html

exclude:
  - Gemfile
  - Gemfile.lock
  - mrdemonwolf.config.js
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json
  - README.md
